-- MySQL Script generated by MySQL Workbench
-- Fri Aug  8 09:19:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vida_mais_saude
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vida_mais_saude` ;

-- -----------------------------------------------------
-- Schema vida_mais_saude
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vida_mais_saude` DEFAULT CHARACTER SET utf8 ;
USE `vida_mais_saude` ;

-- -----------------------------------------------------
-- Table `vida_mais_saude`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vida_mais_saude`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `hash_senha` VARCHAR(162) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `telefone_UNIQUE` ON `vida_mais_saude`.`cliente` (`telefone` ASC) VISIBLE;

CREATE UNIQUE INDEX `cpf_UNIQUE` ON `vida_mais_saude`.`cliente` (`cpf` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `vida_mais_saude`.`cliente` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vida_mais_saude`.`indicador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vida_mais_saude`.`indicador` (
  `id_indicador` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(15) NOT NULL,
  `observacoes` TEXT NULL,
  `id_cliente` INT NOT NULL,
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_indicador`),
  CONSTRAINT `FK_INDICADOR_CLIENTE`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `vida_mais_saude`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_INDICADOR_CLIENTE_idx` ON `vida_mais_saude`.`indicador` (`id_cliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vida_mais_saude`.`especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vida_mais_saude`.`especialidade` (
  `id_especialidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_especialidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vida_mais_saude`.`profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vida_mais_saude`.`profissional` (
  `id_profissional` INT NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `id_especialidade` INT NOT NULL,
  `registro_profissional` VARCHAR(15) NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`id_profissional`),
  CONSTRAINT `FK_PROFISSIONAL_ESPECIALIDADE`
    FOREIGN KEY (`id_especialidade`)
    REFERENCES `vida_mais_saude`.`especialidade` (`id_especialidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `registro_profissional_UNIQUE` ON `vida_mais_saude`.`profissional` (`registro_profissional` ASC) VISIBLE;

CREATE UNIQUE INDEX `telefone_UNIQUE` ON `vida_mais_saude`.`profissional` (`telefone` ASC) VISIBLE;

CREATE INDEX `FK_PROFISSIONAL_ESPECIALIDADE_idx` ON `vida_mais_saude`.`profissional` (`id_especialidade` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vida_mais_saude`.`hora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vida_mais_saude`.`hora` (
  `id_hora` INT NOT NULL,
  `valor` TIME NOT NULL,
  PRIMARY KEY (`id_hora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vida_mais_saude`.`dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vida_mais_saude`.`dia` (
  `id_dia` INT NOT NULL,
  `nome` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_dia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vida_mais_saude`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vida_mais_saude`.`agendamento` (
  `id_agendamento` INT NOT NULL AUTO_INCREMENT,
  `id_profissional` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_hora` INT NOT NULL,
  `id_dia` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id_agendamento`),
  CONSTRAINT `FK_AGENDAMENTO_PROFISSIONAL`
    FOREIGN KEY (`id_profissional`)
    REFERENCES `vida_mais_saude`.`profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AGENDAMENTO_CLIENTE`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `vida_mais_saude`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AGENDAMENTO_HORA`
    FOREIGN KEY (`id_hora`)
    REFERENCES `vida_mais_saude`.`hora` (`id_hora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AGENDAMENTO_DIA`
    FOREIGN KEY (`id_dia`)
    REFERENCES `vida_mais_saude`.`dia` (`id_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_AGENDAMENTO_PROFISSIONAL_idx` ON `vida_mais_saude`.`agendamento` (`id_profissional` ASC) VISIBLE;

CREATE INDEX `FK_AGENDAMENTO_CLIENTE_idx` ON `vida_mais_saude`.`agendamento` (`id_cliente` ASC) VISIBLE;

CREATE INDEX `FK_AGENDAMENTO_HORA_idx` ON `vida_mais_saude`.`agendamento` (`id_hora` ASC) VISIBLE;

CREATE INDEX `FK_AGENDAMENTO_DIA_idx` ON `vida_mais_saude`.`agendamento` (`id_dia` ASC) VISIBLE;

CREATE INDEX `DATA_IDX` ON `vida_mais_saude`.`agendamento` (`data` ASC) VISIBLE;

CREATE UNIQUE INDEX `AGENDAMENTO_UNICO` ON `vida_mais_saude`.`agendamento` (`id_profissional` ASC, `id_hora` ASC, `data` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vida_mais_saude`.`horario_disponivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vida_mais_saude`.`horario_disponivel` (
  `id_hora` INT NOT NULL,
  `id_profissional` INT NOT NULL,
  CONSTRAINT `FK_HD_HORA`
    FOREIGN KEY (`id_hora`)
    REFERENCES `vida_mais_saude`.`hora` (`id_hora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_HD_PROFISSIONAL`
    FOREIGN KEY (`id_profissional`)
    REFERENCES `vida_mais_saude`.`profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_HD_HORA_idx` ON `vida_mais_saude`.`horario_disponivel` (`id_hora` ASC) VISIBLE;

CREATE INDEX `FK_HD_PROFISSIONAL_idx` ON `vida_mais_saude`.`horario_disponivel` (`id_profissional` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vida_mais_saude`.`dia_disponivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vida_mais_saude`.`dia_disponivel` (
  `id_dia` INT NOT NULL,
  `id_profissional` INT NOT NULL,
  CONSTRAINT `FK_DD_DIA`
    FOREIGN KEY (`id_dia`)
    REFERENCES `vida_mais_saude`.`dia` (`id_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DD_PROFISSIONAL`
    FOREIGN KEY (`id_profissional`)
    REFERENCES `vida_mais_saude`.`profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_DD_DIA_idx` ON `vida_mais_saude`.`dia_disponivel` (`id_dia` ASC) VISIBLE;

CREATE INDEX `FK_DD_PROFISSIONAL_idx` ON `vida_mais_saude`.`dia_disponivel` (`id_profissional` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
